import { describe, expect, it } from 'vitest'
import type { Label, ProfileConfig } from '@/lib/api/types'
import { allOf, hasScenes, labelOf, say, styleTypesOf, vocabularyOf } from '@/lib/useProfile'
import blog from '@/test/fixtures/profiles/blog.json'
import music from '@/test/fixtures/profiles/music.json'
import novel from '@/test/fixtures/profiles/novel.json'
import podcast from '@/test/fixtures/profiles/podcast.json'

/*
 * The vocabulary helpers, read against the profiles the app actually ships -
 * as the window receives them, generated by the backend's own test - rather
 * than against a profile made up to suit the helper.
 */
const SHIPPED: [string, ProfileConfig][] = [blog, music, novel, podcast].map((profile) => [
  profile.key,
  profile.config as unknown as ProfileConfig,
])
const studio = music.config as unknown as ProfileConfig

describe('one kind of work', () => {
  it('reads each shipped kind with every list present', () => {
    for (const [key, config] of SHIPPED) {
      expect(config.work_kinds.length, key).toBeGreaterThan(0)
      for (const kind of config.work_kinds) {
        const vocabulary = vocabularyOf(config, kind.key)
        // A kind that can be judged has somewhere to put the verdict.
        expect(vocabulary.statuses.length, `${key}/${kind.key} statuses`).toBeGreaterThan(0)
        expect(vocabulary.version_roles.length, `${key}/${kind.key} roles`).toBeGreaterThan(0)
        // A kind nobody judges - an audio release goes out for a song that
        // was judged - names no axes and so no tiers; one that names axes
        // has somewhere for the total to land.
        expect(vocabulary.tiers.length > 0, `${key}/${kind.key} tiers`).toBe(
          vocabulary.axes.length > 0,
        )
      }
    }
  })

  it('reads a kind the profile does not know as empty rather than as another', () => {
    const nothing = vocabularyOf(studio, 'sculpture')
    const { cover, frame, made_title, ...lists } = nothing
    expect(Object.values(lists).every((list) => list.length === 0)).toBe(true)
    expect([cover, frame, made_title]).toEqual([false, false, null])
    expect(vocabularyOf(studio, undefined)).toEqual(nothing)
  })

  it('keeps the vocabularies of two kinds apart', () => {
    const song = vocabularyOf(studio, 'song').axes.map((axis) => axis.key)
    const video = vocabularyOf(studio, 'video').axes.map((axis) => axis.key)
    expect(song).toContain('hook')
    expect(video).not.toContain('hook')
  })
})

describe('storyboards', () => {
  it('belong to the kinds that name shots or prompt blocks', () => {
    expect(hasScenes(studio, 'song')).toBe(false)
    expect(hasScenes(studio, 'video')).toBe(true)
    expect(hasScenes(studio, 'short')).toBe(true)
    expect(hasScenes(studio, undefined)).toBe(false)
  })
})

describe('every kind at once', () => {
  it('lists each key once, in the order the kinds first name it', () => {
    const statuses = allOf(studio, 'statuses').map((status) => status.key)
    expect(new Set(statuses).size).toBe(statuses.length)
    const everywhere = new Set(
      studio.work_kinds.flatMap((kind) => (kind.statuses ?? []).map((s) => s.key)),
    )
    expect(new Set(statuses)).toEqual(everywhere)
  })

  it('takes the first label a key was given', () => {
    const config: ProfileConfig = {
      ...studio,
      work_kinds: [
        {
          ...studio.work_kinds[0]!,
          statuses: [{ key: 'draft', label: 'First', derive: 'manual' }],
        },
        {
          ...studio.work_kinds[1]!,
          statuses: [{ key: 'draft', label: 'Second', derive: 'manual' }],
        },
      ],
    }
    expect(allOf(config, 'statuses')).toEqual([{ key: 'draft', label: 'First', derive: 'manual' }])
  })
})

describe('style types', () => {
  it('are the profile’s, and a craft without them has none', () => {
    expect(styleTypesOf(studio).map((type) => type.key)).toContain('character')
    const plain = blog.config as unknown as ProfileConfig
    expect(styleTypesOf(plain)).toEqual([])
  })
})

describe('saying a word', () => {
  it('says a map in the language asked for, then English, then whatever it holds', () => {
    expect(say({ en: 'Draft', ru: 'Черновик' }, 'ru')).toBe('Черновик')
    expect(say({ en: 'Draft', ru: 'Черновик' }, 'de')).toBe('Draft')
    expect(say({ ru: 'Черновик' }, 'en')).toBe('Черновик')
  })

  it('keeps a word the author typed exactly as typed, in any language', () => {
    expect(say('Набросок', 'en')).toBe('Набросок')
  })

  it('shows the key for a word the profile does not have, never a blank', () => {
    expect(labelOf([{ key: 'draft', label: 'Draft' }], 'shelved')).toBe('shelved')
    expect(labelOf([{ key: 'draft', label: 'Draft' }], 'draft')).toBe('Draft')
  })
})

/** Every `label` in a profile document, with where it was found. */
function labelsIn(value: unknown, path: string, out: [string, Label][]): [string, Label][] {
  if (Array.isArray(value)) {
    value.forEach((item, index) => labelsIn(item, `${path}[${index}]`, out))
  } else if (typeof value === 'object' && value !== null) {
    for (const [key, inner] of Object.entries(value)) {
      if (key === 'label') out.push([path, inner as Label])
      else labelsIn(inner, `${path}.${key}`, out)
    }
  }
  return out
}

describe('the shipped profiles', () => {
  it('are translated whole or not at all, never a word here and there', () => {
    // A half-translated profile is the worst of both: a Russian window reads
    // a status in Russian beside a tier in English. The Studio profile is in
    // both languages; the other three are English for now, which a Russian
    // window shows as typed rather than as a gap.
    const bilingual = (label: Label) => typeof label !== 'string' && !!label.en && !!label.ru
    const translated: string[] = []
    for (const [key, config] of SHIPPED) {
      const labels = labelsIn(config, key, [])
      expect(labels.length, key).toBeGreaterThan(20)
      const halves = labels.filter(([, label]) => bilingual(label)).length
      expect(
        [0, labels.length],
        `${key}: ${halves} of ${labels.length} words translated`,
      ).toContain(halves)
      if (halves > 0) translated.push(key)
    }
    expect(translated).toContain('music')
  })
})
