import type {
  Asset,
  CardCounts,
  CardSummary,
  CardView,
  Fact,
  ChatSummary,
  Collection,
  Comment,
  Cut,
  Deletion,
  Derived,
  Cover,
  CoverView,
  FrameView,
  Going,
  Publication,
  Publications,
  JournalEntry,
  Link,
  Links,
  Moment,
  Note,
  Profile,
  ProfileConfig,
  Readiness,
  Release,
  Scene,
  ScheduledRelease,
  Score,
  ScoredWork,
  StyleBrick,
  Version,
  VersionSummary,
  Work,
} from '@/lib/api/types'
import type { Args, Handler } from '@/test/backend'
import music from '@/test/fixtures/profiles/music.json'

/*
 * A small studio, made up: two songs, the clip cut to the first and a short
 * cut from the clip. Every name is invented and English, as the project's
 * rule on demo data asks - nothing here is anyone's real work.
 *
 * The vocabulary is the shipped Studio profile, read the way the window reads
 * it (`fixtures/profiles/`, generated by the backend's own tests), so a
 * screen is drawn with the kinds, roles and axes a person actually has.
 */

/** The moment the fixture was "made": fixed, so a date on screen is too. */
export const NOW = '2026-09-15T10:00:00Z'
const EARLIER = '2026-09-01T10:00:00Z'

export const IDS = {
  profile: 'p-studio',
  song: 'w-lanterns',
  draft: 'w-harbour',
  video: 'w-lanterns-clip',
  short: 'w-lanterns-short',
  /** The song's audio release, a work of its own since v0.86. */
  audio: 'w-lanterns-audio',
  lyrics: 'v-lanterns-lyrics-2',
  lyricsFirst: 'v-lanterns-lyrics-1',
  style: 'v-lanterns-style',
  draftLyrics: 'v-harbour-lyrics',
  plot: 'v-clip-plot',
  score: 's-lanterns',
  audioRelease: 'r-lanterns-audio',
  youtube: 'r-clip-youtube',
  note: 'n-idea',
  character: 'n-keeper',
  comment: 'c-first',
  brick: 'b-dusk',
  sceneOpen: 'sc-open',
  sceneClose: 'sc-close',
  cut: 'cut-chorus',
  link: 'l-clip-from-song',
  audioLink: 'l-audio-from-song',
  collection: 'col-first',
} as const

export interface Studio {
  profile: Profile
  works: Work[]
  versions: Version[]
  scores: Score[]
  releases: Release[]
  notes: Note[]
  /** The facts of the canon's cards. */
  facts: Fact[]
  comments: Comment[]
  bricks: StyleBrick[]
  scenes: Scene[]
  cuts: Cut[]
  links: Link[]
  collections: Collection[]
  journal: JournalEntry[]
  deletions: Deletion[]
  chats: ChatSummary[]
}

/** A cover with nothing in it, the way `Cover` reads `{}` on the Rust side;
 *  `fields` fills in what a fixture says. */
export function coverOf(fields: Partial<Cover> = {}): Cover {
  return {
    idea: '',
    scene: '',
    avoid: '',
    hero: null,
    framing: null,
    bricks: { style: null, typography: null, dressing: null, background: null },
    accent: null,
    lettering: { title: null, apart: false, captions: {} },
    mark: { variant: null, place: 'corner', corner: 'bottomRight', way: 'overlay' },
    details: {},
    picture: '',
    negative: '',
    typography: '',
    sent: null,
    ...fields,
  }
}

function work(fields: Partial<Work> & Pick<Work, 'id' | 'kind' | 'title'>): Work {
  return {
    profile_id: IDS.profile,
    collection_id: null,
    status: 'draft',
    status_pinned_at: null,
    meta: {},
    tags: [],
    marks: [],
    current_version_id: null,
    position: 0,
    tier_pinned: null,
    tier_pinned_at: null,
    tier_pin_reason: null,
    bookmarked_at: null,
    stage: null,
    cover: coverOf(),
    frame: {
      still: '',
      motion: '',
      seconds: 6,
      still_camera: true,
      seamless: true,
      negative: '',
      built: null,
      framing: null,
    },
    created_at: EARLIER,
    updated_at: NOW,
    ...fields,
  }
}

function version(
  fields: Partial<Version> & Pick<Version, 'id' | 'work_id' | 'role' | 'body'>,
): Version {
  return {
    revision: 1,
    label: null,
    meta: {},
    parent_version_id: null,
    created_at: EARLIER,
    ...fields,
  }
}

function release(fields: Partial<Release> & Pick<Release, 'id' | 'work_id' | 'kind'>): Release {
  return {
    status: 'planned',
    scheduled_at: null,
    released_at: null,
    url: null,
    slot_pinned_at: null,
    scheduled_time: null,
    time_zone: null,
    meta: {},
    created_at: EARLIER,
    updated_at: NOW,
    ...fields,
  }
}

/** A fresh studio: each call builds its own, so a test may change it freely. */
export function studio(): Studio {
  const profile: Profile = {
    id: IDS.profile,
    key: music.key,
    name: music.name,
    description: music.description,
    config: music.config as unknown as ProfileConfig,
    is_active: true,
    is_builtin: true,
  }

  const works = [
    work({
      id: IDS.song,
      kind: 'song',
      title: 'Paper Lanterns',
      status: 'scored',
      tags: ['night'],
      marks: ['working'],
      stage: 50,
      current_version_id: IDS.lyrics,
      collection_id: IDS.collection,
      meta: { bpm: '96', key: 'A minor', duration: '3:24', language: 'en' },
      position: 0,
    }),
    work({
      id: IDS.draft,
      kind: 'song',
      title: 'Harbour Lights',
      current_version_id: IDS.draftLyrics,
      position: 1,
    }),
    work({
      id: IDS.video,
      kind: 'video',
      title: 'Paper Lanterns (clip)',
      current_version_id: IDS.plot,
      meta: { duration: '3:24' },
      position: 2,
    }),
    work({ id: IDS.short, kind: 'short', title: 'Paper Lanterns (short)', position: 3 }),
    work({
      id: IDS.audio,
      kind: 'audio',
      title: 'Paper Lanterns — audio',
      status: 'scheduled',
      meta: { bpm: '96', variant: 'original' },
      cover: coverOf({ picture: 'a paper lantern on dark water, seen from above' }),
      frame: {
        still: 'a paper lantern on dark water at dusk, seen from above',
        motion: 'the lantern turns slowly on the current',
        seconds: 6,
        still_camera: true,
        seamless: true,
        negative: 'no people',
        built: null,
        framing: null,
      },
      position: 4,
    }),
  ]

  const versions = [
    version({
      id: IDS.lyricsFirst,
      work_id: IDS.song,
      role: 'lyrics',
      body: 'Lanterns on the water\nfloating out of reach',
    }),
    version({
      id: IDS.lyrics,
      work_id: IDS.song,
      role: 'lyrics',
      revision: 2,
      label: 'Second pass',
      parent_version_id: IDS.lyricsFirst,
      body: '[Verse]\nLanterns on the water\nfloating out of reach\n\n[Chorus]\nPaper, paper, carry the light',
      created_at: NOW,
    }),
    version({
      id: IDS.style,
      work_id: IDS.song,
      role: 'style',
      body: 'warm synth pop, slow build, airy female vocal',
    }),
    version({
      id: IDS.draftLyrics,
      work_id: IDS.draft,
      role: 'lyrics',
      body: 'Harbour lights are blinking\none by one',
    }),
    version({
      id: IDS.plot,
      work_id: IDS.video,
      role: 'plot',
      body: 'A girl lets a paper lantern go at dusk; the river carries it through the town.',
    }),
  ]

  const scores: Score[] = [
    {
      id: IDS.score,
      work_id: IDS.song,
      version_id: IDS.lyrics,
      axes: { hook: 8, lyrics: 7, emotion: 8, production: 6, originality: 7, visual: 9 },
      total: 7.5,
      tier: 'picture',
      note: 'The chorus carries it.',
      rater: null,
      scored_at: NOW,
      revision: 2,
    },
  ]

  const releases = [
    release({
      id: IDS.audioRelease,
      work_id: IDS.audio,
      kind: 'youtube',
      status: 'planned',
      scheduled_at: '2026-09-22',
    }),
    release({ id: IDS.youtube, work_id: IDS.video, kind: 'youtube' }),
  ]

  const notes: Note[] = [
    {
      id: IDS.note,
      profile_id: IDS.profile,
      work_id: null,
      kind: 'note',
      title: 'A song about tides',
      body: 'Something about the tide going out and taking the day with it.\n\n- [ ] find a hook',
      tags: ['ideas'],
      created_at: EARLIER,
      updated_at: NOW,
      layer: 'public',
      aliases: [],
      prompt: null,
      prompt_basis: null,
      state: 'fresh',
    },
    {
      id: IDS.character,
      profile_id: IDS.profile,
      work_id: IDS.video,
      kind: 'character',
      title: 'The lantern keeper',
      body: 'An old man who sells lanterns by the bridge.',
      tags: [],
      created_at: EARLIER,
      updated_at: EARLIER,
      layer: 'public',
      aliases: ['the keeper'],
      prompt: 'an old man in a grey coat with a pole of paper lanterns',
      prompt_basis: 'f00d',
      state: 'fresh',
    },
  ]

  const comments: Comment[] = [
    {
      id: IDS.comment,
      profile_id: IDS.profile,
      channel: 'YouTube',
      work_id: IDS.video,
      author: 'listener42',
      body: 'The shot on the bridge is beautiful.',
      reply: null,
      state: 'open',
      commented_on: '2026-09-14',
      created_at: NOW,
      updated_at: NOW,
    },
  ]

  const bricks: StyleBrick[] = [
    {
      id: IDS.brick,
      profile_id: IDS.profile,
      type_key: 'look',
      name: 'Dusk over water',
      description: 'Low sun, long reflections, teal and amber.',
      hint: null,
      status: 'ready',
      created_at: EARLIER,
      updated_at: NOW,
      reference_count: 0,
      label: null,
      family: null,
      when_to_use: null,
      colours: [],
      sample: null,
      set_key: null,
      origin: 'own',
    },
  ]

  const scenes: Scene[] = [
    {
      id: IDS.sceneOpen,
      profile_id: IDS.profile,
      work_id: IDS.video,
      position: 1,
      section: 'Verse',
      starts_at: 0,
      ends_at: 12,
      shot_type: null,
      description: 'The lantern is lit on the riverbank.',
      blocks: { still: 'close-up of hands lighting a paper lantern at dusk' },
      framing: null,
      created_at: EARLIER,
      updated_at: NOW,
    },
    {
      id: IDS.sceneClose,
      profile_id: IDS.profile,
      work_id: IDS.video,
      position: 2,
      section: 'Chorus',
      starts_at: 12,
      ends_at: 30,
      shot_type: null,
      description: 'The lantern drifts under the bridge.',
      blocks: {},
      framing: null,
      created_at: EARLIER,
      updated_at: NOW,
    },
  ]

  const cuts: Cut[] = [
    {
      id: IDS.cut,
      profile_id: IDS.profile,
      work_id: IDS.short,
      source_id: IDS.video,
      starts_at: 12,
      ends_at: 30,
      position: 0,
      label: 'Chorus',
      created_at: EARLIER,
      updated_at: NOW,
      source_title: 'Paper Lanterns (clip)',
      source_duration: 204,
    },
  ]

  const links: Link[] = [
    {
      id: IDS.link,
      work_id: IDS.video,
      source_id: IDS.song,
      role: 'soundtrack',
      source_version_id: IDS.lyrics,
      created_at: EARLIER,
      source_title: 'Paper Lanterns',
      source_kind: 'song',
      source_status: 'scored',
      source_current_version_id: IDS.lyrics,
      taken_revision: 2,
      current_revision: 2,
      drifted: false,
    },
    {
      id: IDS.audioLink,
      work_id: IDS.audio,
      source_id: IDS.song,
      role: 'donor',
      source_version_id: IDS.lyrics,
      created_at: EARLIER,
      source_title: 'Paper Lanterns',
      source_kind: 'song',
      source_status: 'scored',
      source_current_version_id: IDS.lyrics,
      taken_revision: 2,
      current_revision: 2,
      drifted: false,
    },
  ]

  const collections: Collection[] = [
    {
      id: IDS.collection,
      profile_id: IDS.profile,
      kind: 'album',
      title: 'Riverside',
      description: null,
      position: 0,
      meta: {},
      target_size: 8,
      due_on: null,
      created_at: EARLIER,
      updated_at: NOW,
      works: 1,
    },
  ]

  const journal: JournalEntry[] = [
    {
      id: 'j-created',
      action: 'work.created',
      params: { title: 'Harbour Lights' },
      level: 'info',
      entity: 'work',
      entity_id: IDS.draft,
      occurrences: 1,
      created_at: NOW,
      read_at: null,
    },
    {
      id: 'j-scored',
      action: 'score.added',
      params: { title: 'Paper Lanterns', total: 7.5 },
      level: 'info',
      entity: 'work',
      entity_id: IDS.song,
      occurrences: 1,
      created_at: EARLIER,
      read_at: EARLIER,
    },
  ]

  const deletions: Deletion[] = [
    {
      id: 'd-old-note',
      entity: 'note',
      entity_id: 'n-old',
      label: 'An old idea',
      origin: null,
      work_id: null,
      reason: 'deleted',
      deleted_at: NOW,
      restorable: true,
    },
  ]

  // The lantern keeper is a card of the canon (ADR 0043): a character of the
  // Studio profile, with a fact of his looks and one of his past.
  const facts: Fact[] = [
    {
      id: 'f-keeper-coat',
      profile_id: IDS.profile,
      note_id: IDS.character,
      section: 'looks',
      body: 'A long grey coat and a pole hung with paper lanterns.',
      layer: 'public',
      status: 'canon',
      retired_reason: null,
      source: null,
      when: null,
      scope_work_id: null,
      data: {},
      position: 1,
      created_at: EARLIER,
      updated_at: EARLIER,
    },
    {
      id: 'f-keeper-bridge',
      profile_id: IDS.profile,
      note_id: IDS.character,
      section: 'bio',
      body: 'Has sold lanterns by the bridge since the flood.',
      layer: 'internal',
      status: 'draft',
      retired_reason: null,
      source: null,
      when: { label: 'autumn 1998', sort: '1998-09' },
      scope_work_id: null,
      data: {},
      position: 1,
      created_at: EARLIER,
      updated_at: EARLIER,
    },
  ]

  const chats: ChatSummary[] = [
    {
      id: 'chat-lanterns',
      work_id: IDS.song,
      work_title: 'Paper Lanterns',
      title: 'Tighten the chorus',
      first_prompt: 'Tighten the chorus',
      cost_usd: 0.02,
      updated_at: NOW,
    },
  ]

  return {
    profile,
    works,
    versions,
    scores,
    releases,
    notes,
    facts,
    comments,
    bricks,
    scenes,
    cuts,
    links,
    collections,
    journal,
    deletions,
    chats,
  }
}

const byWork =
  <T extends { work_id: string | null }>(rows: () => T[]) =>
  ({ workId }: Args) =>
    rows().filter((row) => row.work_id === workId)

/** Whether a song has what its release needs: the tests do not judge it. */
const READY: Readiness = { roles: [], scored: true, ready: true }

function scheduled(studio: Studio, release: Release): ScheduledRelease {
  const owner = studio.works.find((w) => w.id === release.work_id)
  const score = studio.scores.find((s) => s.work_id === release.work_id)
  return {
    ...release,
    work_title: owner?.title ?? '',
    work_kind: owner?.kind ?? '',
    total: score?.total ?? null,
    tier: score?.tier ?? null,
    readiness: READY,
    work_stage: owner?.stage ?? null,
  }
}

function summary(studio: Studio, row: Version): VersionSummary {
  const owner = studio.works.find((w) => w.id === row.work_id)
  return {
    id: row.id,
    work_id: row.work_id,
    role: row.role,
    revision: row.revision,
    label: row.label,
    length: row.body.length,
    parent_version_id: row.parent_version_id,
    created_at: row.created_at,
    is_current: owner?.current_version_id === row.id,
    about_version_id: null,
  }
}

function scored(studio: Studio, row: Work): ScoredWork {
  const score = studio.scores.find((s) => s.work_id === row.id)
  const publications = studio.links
    .filter((link) => link.source_id === row.id)
    .map((l) => l.work_id)
  // A work with no door counts its publications' releases as its own, the
  // way `score::catalogue` reads a song since v0.86: the song is booked when
  // its audio is.
  const doorless = !studio.profile.config.work_kinds.some(
    (known) => known.key === row.kind && (known.release_kinds ?? []).length > 0,
  )
  const speaking = new Set(doorless ? [row.id, ...publications] : [row.id])
  const releases = studio.releases.filter((r) => speaking.has(r.work_id))
  return {
    work_id: row.id,
    title: row.title,
    kind: row.kind,
    status: row.status,
    tier_pinned: row.tier_pinned !== null,
    total: score?.total ?? null,
    tier: row.tier_pinned ?? score?.tier ?? null,
    scored_at: score?.scored_at ?? null,
    stale: false,
    released: releases.filter((r) => r.released_at !== null).length,
    scheduled: releases.filter((r) => r.scheduled_at !== null).length,
    updated_at: row.updated_at,
    created_at: row.created_at,
    collection_id: row.collection_id,
    tags: row.tags,
    marks: row.marks,
    bookmarked_at: row.bookmarked_at,
    version_count: studio.versions.filter((v) => v.work_id === row.id).length,
    stage: row.stage,
    publications,
  }
}

function linksOf(studio: Studio, workId: string): Links {
  return {
    sources: studio.links.filter((link) => link.work_id === workId),
    derived: studio.links
      .filter((link) => link.source_id === workId)
      .map((link) => {
        const derived = studio.works.find((w) => w.id === link.work_id)
        return {
          link_id: link.id,
          work_id: link.work_id,
          title: derived?.title ?? '',
          kind: derived?.kind ?? '',
          status: derived?.status ?? '',
          role: link.role,
          created_at: link.created_at,
          ...releasesOf(studio, link.work_id),
        }
      }),
  }
}

/** Where a derived work's releases stand, the way `link::derived` reads it. */
function releasesOf(
  studio: Studio,
  workId: string,
): Pick<Derived, 'released' | 'last_released_at' | 'next_scheduled_at'> {
  const mine = studio.releases.filter((r) => r.work_id === workId)
  const out = mine.filter((r) => r.status === 'released' && r.released_at !== null)
  const waiting = mine
    .filter((r) => r.status !== 'released' && r.scheduled_at !== null)
    .map((r) => r.scheduled_at!)
    .sort()
  return {
    released: out.length,
    last_released_at:
      out
        .map((r) => r.released_at!)
        .sort()
        .at(-1) ?? null,
    next_scheduled_at: waiting[0] ?? null,
  }
}

/** A publication's one release, as `publication::of` reads it (ADR 0051). */
function goingOf(studio: Studio, workId: string): Going | null {
  const found = studio.releases.find((r) => r.work_id === workId)
  if (found === undefined) return null
  return {
    id: found.id,
    kind: found.kind,
    status: found.status,
    scheduled_at: found.scheduled_at,
    scheduled_time: found.scheduled_time,
    released_at: found.released_at,
    url: found.url,
  }
}

/** What was made from a work, read off the studio as `publication::of` would:
 *  directly made works only - the studio has no second step down. */
/**
 * A work's axis read off the studio the way `work::timeline` reads the
 * database: its beginning, its versions and scores, what was made from it and
 * the day each goes out, and the journal's lines no row holds - latest first.
 */
function timelineOf(studio: Studio, workId: string): Moment[] {
  const owner = studio.works.find((w) => w.id === workId)
  if (owner === undefined) return []
  const versions = studio.versions.filter((v) => v.work_id === workId)
  const revisionOf = (id: string | null) => versions.find((v) => v.id === id)
  const moments: Moment[] = [{ type: 'begun', at: owner.created_at }]
  for (const v of versions) {
    moments.push({
      type: 'version',
      at: v.created_at,
      id: v.id,
      role: v.role,
      revision: v.revision,
      label: v.label,
      parent: revisionOf(v.parent_version_id)?.revision ?? null,
    })
  }
  for (const score of studio.scores.filter((one) => one.work_id === workId)) {
    const read = revisionOf(score.version_id)
    moments.push({
      type: 'score',
      at: score.scored_at,
      id: score.id,
      total: score.total,
      tier: score.tier,
      rater: score.rater,
      version_id: score.version_id,
      role: read?.role ?? null,
      revision: read?.revision ?? null,
    })
  }
  const going = (release: Release, title: string) => {
    const released = release.status === 'released'
    const at = released ? release.released_at : release.scheduled_at
    if (at === null) return
    moments.push({
      type: 'release',
      at,
      id: release.id,
      work_id: release.work_id,
      title,
      kind: release.kind,
      released,
      time: release.scheduled_time,
      url: release.url,
    })
  }
  for (const own of studio.releases.filter((r) => r.work_id === workId)) going(own, owner.title)
  for (const link of studio.links.filter((one) => one.source_id === workId)) {
    const made = studio.works.find((w) => w.id === link.work_id)
    if (made === undefined) continue
    moments.push({
      type: 'made',
      at: made.created_at,
      work_id: made.id,
      title: made.title,
      kind: made.kind,
      depth: 1,
    })
    for (const release of studio.releases.filter((r) => r.work_id === made.id)) {
      going(release, made.title)
    }
  }
  const said = new Set(['work.created', 'version.created', 'score.added', 'release.released'])
  for (const entry of studio.journal) {
    if (entry.entity_id === workId && !said.has(entry.action)) {
      moments.push({ type: 'entry', at: entry.created_at, entry })
    }
  }
  return moments.sort((a, b) => b.at.localeCompare(a.at))
}

function publicationsOf(studio: Studio, workId: string): Publications {
  const items: Publication[] = studio.links
    .filter((link) => link.source_id === workId)
    .map((link) => {
      const made = studio.works.find((w) => w.id === link.work_id)!
      const comments = studio.comments.filter(
        (c) => c.work_id === made.id && c.state !== 'archived',
      )
      return {
        work_id: made.id,
        title: made.title,
        kind: made.kind,
        status: made.status,
        stage: made.stage,
        depth: 1,
        via: null,
        release: goingOf(studio, made.id),
        comments: comments.length,
        comments_waiting: comments.filter((c) => c.state === 'open').length,
        created_at: made.created_at,
      }
    })
  const booked = items
    .filter((item) => item.release?.status !== 'released' && item.release?.scheduled_at != null)
    .sort((a, b) => a.release!.scheduled_at!.localeCompare(b.release!.scheduled_at!))[0]
  return {
    items,
    basis:
      booked === undefined
        ? null
        : {
            work_id: booked.work_id,
            title: booked.title,
            kind: booked.kind,
            released: false,
            day: booked.release!.scheduled_at!,
          },
  }
}

/** The frame as `frame_view` gives it for a frame written whole: the blocks
 *  written the way `Frame::prompts` writes them, no scheme. A frame built
 *  from its cover is answered by a test that needs one. */
function frameViewOf(studio: Studio, workId: string): FrameView {
  const frame = studio.works.find((w) => w.id === workId)?.frame
  const motion = frame?.motion.trim() || 'barely noticeable breathing of the light'
  return {
    prompts: {
      still: frame?.still ?? '',
      loop: `LOOP (${frame?.seconds ?? 6} s): ${motion}.`,
      negative: frame?.negative ?? '',
    },
    from_cover: false,
    format: '16:9',
    scheme: null,
    layouts: [],
    details: [],
    problems: [],
  }
}

/** The Cover tab of a work, as `cover_view` gives it for a cover written by
 *  hand: its own words are its prompt, and its kind's doors its shapes. */
function coverViewOf(studio: Studio, workId: string, format: string | null): CoverView {
  const found = studio.works.find((w) => w.id === workId)
  const cover = found?.cover ?? coverOf()
  const kind = studio.profile.config.work_kinds.find((k) => k.key === found?.kind)
  const held = new Set(studio.releases.filter((r) => r.work_id === workId).map((r) => r.kind))
  const formats = (kind?.release_kinds ?? [])
    .filter((door) => (door.cover_format ?? null) !== null)
    .map((door) => ({
      door: door.key,
      label: door.label,
      format: door.cover_format!,
      held: held.has(door.key),
    }))
  return {
    built: false,
    prompts: {
      picture: cover.picture,
      negative: cover.negative,
      typography: cover.typography === '' ? null : cover.typography,
    },
    format: format ?? formats.find((f) => f.held)?.format ?? formats[0]?.format ?? '1:1',
    formats,
    scheme: null,
    layouts: [],
    title: found?.title ?? '',
    source_title: found?.title ?? '',
    slots: [],
    details: [],
    marks: [],
    palette: [],
    house_styles: [],
    hero: null,
    references: [],
    problems: [],
    sent_differs: false,
    mark_box: null,
  }
}

/** The numbers beside a card's tabs, read off the studio as `card::counts` would. */
function countsOf(studio: Studio, workId: string): CardCounts {
  const mine = <T extends { work_id: string | null }>(rows: T[]) =>
    rows.filter((row) => row.work_id === workId).length
  // A work that never goes out itself - a song - counts the comments under
  // what was made from it, the way `card::counts` does since v0.86.
  const kind = studio.works.find((w) => w.id === workId)?.kind
  const goesOut = studio.profile.config.work_kinds.some(
    (known) => known.key === kind && (known.release_kinds ?? []).length > 0,
  )
  const heard = goesOut
    ? new Set([workId])
    : new Set([workId, ...publicationsOf(studio, workId).items.map((item) => item.work_id)])
  const comments = studio.comments.filter(
    (c) => c.work_id !== null && heard.has(c.work_id) && c.state !== 'archived',
  )
  return {
    versions: mine(studio.versions),
    scores: mine(studio.scores),
    releases: mine(studio.releases),
    // No files are attached in this studio: `list_work_assets` answers none.
    files: 0,
    sources: mine(studio.links),
    derived: studio.links.filter((link) => link.source_id === workId).length,
    notes: mine(studio.notes),
    comments: comments.length,
    comments_waiting: comments.filter((c) => c.state === 'open').length,
    scenes: mine(studio.scenes),
    cuts: mine(studio.cuts),
    cut_from: studio.cuts.filter((cut) => cut.source_id === workId).length,
    // The axis without its beginning, as `work::timeline::count` counts it.
    history: Math.max(timelineOf(studio, workId).length - 1, 0),
  }
}

function counted(values: string[]): [string, number][] {
  const counts = new Map<string, number>()
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1)
  return [...counts.entries()].sort(([a], [b]) => a.localeCompare(b))
}

/** Whether notes of this kind are cards of the canon: the kind has sections. */
function isCard(studio: Studio, kind: string): boolean {
  return (studio.profile.config.note_kinds ?? []).some(
    (one) => one.key === kind && (one.sections ?? []).length > 0,
  )
}

/** Whether notes of `kind` are lines, kept in a bank of their own (ADR 0045). */
function isLineKind(studio: Studio, kind: string): boolean {
  return (studio.profile.config.note_kinds ?? []).some(
    (one) => one.key === kind && one.line === true,
  )
}

/** A card as the list shows it, read off the studio as `canon::view::cards` would. */
function cardOf(studio: Studio, note: Note): CardSummary {
  const own = studio.facts.filter((fact) => fact.note_id === note.id)
  return {
    id: note.id,
    kind: note.kind,
    title: note.title,
    work_id: note.work_id,
    work_title: studio.works.find((w) => w.id === note.work_id)?.title ?? null,
    layer: note.layer,
    aliases: note.aliases,
    facts: own.filter((fact) => fact.status !== 'retired').length,
    drafts: own.filter((fact) => fact.status === 'draft').length,
    open: own.filter((fact) => fact.status === 'open').length,
    portrait: null,
    updated_at: note.updated_at,
  }
}

/** A card whole, read off the studio as `canon::view::card` would. The
 *  lenses follow the backend's rule for the two facts the studio has. */
function viewOf(studio: Studio, note: Note): CardView {
  return {
    card: note,
    work_title: studio.works.find((w) => w.id === note.work_id)?.title ?? null,
    facts: studio.facts
      .filter((fact) => fact.note_id === note.id)
      .map((fact) => ({
        fact,
        lenses:
          fact.layer === 'public' && fact.status === 'canon' && fact.section === 'looks'
            ? ['cover', 'work']
            : ['work'],
      })),
    relations: [],
    pictures: [],
    appearances: [],
    basis: 'f00d',
    prompt_stale: false,
    lenses: ['cover', 'work', 'public'],
  }
}

/**
 * The answers to every question a screen asks on its way in, read off the
 * studio. Reads only: a test about a write answers that command itself, and
 * says what the write should have been.
 */
export function answersFor(studio: Studio): Record<string, Handler> {
  const noAssets: Asset[] = []
  return {
    get_workspace: () => ({
      schema_version: 30,
      profile: studio.profile,
      works: studio.works.length,
      releases: studio.releases.length,
    }),
    list_profiles: () => [studio.profile],
    warn_unready_releases: () => 0,
    last_undoable: () => null,

    catalogue: () => studio.works.map((row) => scored(studio, row)),
    list_works: () => studio.works,
    get_work: ({ id }) => studio.works.find((w) => w.id === id) ?? null,
    card_counts: ({ workId }) => countsOf(studio, workId as string),
    work_timeline: ({ workId }) => timelineOf(studio, workId as string),
    work_tags: () => counted(studio.works.flatMap((w) => w.tags)),
    works_matching: () => [],
    search: () => [],
    status_drift: () => [],
    list_collections: () => studio.collections,
    list_covers: () => [],

    // Ordered as `version::list` orders them: by role, newest first within
    // one - the order the list is drawn in and the tree is laid out over.
    list_versions: ({ workId }) =>
      studio.versions
        .filter((v) => v.work_id === workId)
        .sort((a, b) => a.role.localeCompare(b.role) || b.revision - a.revision)
        .map((v) => summary(studio, v)),
    get_version: ({ id }) => studio.versions.find((v) => v.id === id) ?? null,
    resolve_links: () => [],

    score_history: byWork(() => studio.scores),
    latest_score: ({ workId }) => studio.scores.find((s) => s.work_id === workId) ?? null,
    kind_verdicts: () => [],

    calendar: () =>
      studio.releases.filter((r) => r.scheduled_at !== null).map((r) => scheduled(studio, r)),
    release_queue: () =>
      studio.releases.filter((r) => r.scheduled_at === null).map((r) => scheduled(studio, r)),
    releases_for_work: ({ workId }) =>
      studio.releases.filter((r) => r.work_id === workId).map((r) => scheduled(studio, r)),
    release_fields: () => [],
    list_release_assets: () => noAssets,
    can_export_package: () => true,

    list_links: ({ workId }) => linksOf(studio, workId as string),
    list_publications: ({ workId }) => publicationsOf(studio, workId as string),
    frame_view: ({ id }) => frameViewOf(studio, id as string),
    // A board with nothing on it yet: the smoke opens the Cover tab on its
    // ideas, and a cover's own tests give it the cards they need.
    cover_board: () => ({ format: '16:9', ideas: [], siblings: [] }),
    cover_view: ({ id, format }) =>
      coverViewOf(studio, id as string, (format as string | null | undefined) ?? null),
    release_proposals: () => [],
    list_scenes: byWork(() => studio.scenes),
    list_scene_notes: () => [],
    list_scene_frames: () => [],
    list_cuts: byWork(() => studio.cuts),
    list_cuts_from: ({ sourceId }) => studio.cuts.filter((c) => c.source_id === sourceId),
    cut_shot_list: () => [],
    list_work_assets: () => noAssets,

    list_notes: ({ filter }) => {
      const wanted = (filter ?? {}) as {
        work_id?: string | null
        kind?: string | null
        tag?: string | null
        canon?: boolean | null
        line?: boolean | null
        state?: string | null
      }
      return studio.notes.filter(
        (note) =>
          (wanted.work_id == null || note.work_id === wanted.work_id) &&
          (wanted.kind == null || note.kind === wanted.kind) &&
          (wanted.tag == null || note.tags.includes(wanted.tag)) &&
          (wanted.canon == null || isCard(studio, note.kind) === wanted.canon) &&
          (wanted.line == null || isLineKind(studio, note.kind) === wanted.line) &&
          (wanted.state == null || note.state === wanted.state),
      )
    },

    // The register of repeats: empty, and every text checked against it
    // finds nothing - a screen that shows a version asks for both.
    list_terms: () => [],
    list_term_topics: () => [],
    term_uses: () => [],
    preview_term: () => 0,
    check_text: () => ({ repeats: [], terms: [], marks: [], stress: [], accents: [] }),
    clean_text: ({ text }) => text,
    // The bank of words and the guard of repeats (v0.90): empty until a
    // test says otherwise.
    list_blocks: () => [],
    words_from_texts: () => ({ words: [] }),
    repeat_marks: () => [],
    work_repeats: () => null,

    list_cards: () =>
      studio.notes.filter((note) => isCard(studio, note.kind)).map((note) => cardOf(studio, note)),
    read_card: ({ id }) => {
      const note = studio.notes.find((one) => one.id === id)
      return note === undefined ? Promise.reject(new Error('no such card')) : viewOf(studio, note)
    },
    card_as_seen: () => '## The lantern keeper',
    canon_timeline: () =>
      studio.facts
        .filter((fact) => fact.when?.sort !== undefined)
        .map((fact) => {
          const card = studio.notes.find((note) => note.id === fact.note_id)
          return {
            fact,
            card_title: card?.title ?? null,
            card_kind: card?.kind ?? 'character',
            card_layer: card?.layer ?? 'public',
            lenses: ['work'],
          }
        }),
    pending_canon_proposals: () => [],
    list_tags: () => counted(studio.notes.flatMap((n) => n.tags)),

    list_comments: ({ filter }) => {
      const wanted = (filter ?? {}) as { work_id?: string | null; under?: string | null }
      const made =
        wanted.under == null
          ? null
          : new Set(publicationsOf(studio, wanted.under).items.map((item) => item.work_id))
      return studio.comments.filter(
        (c) =>
          (wanted.work_id == null || c.work_id === wanted.work_id) &&
          (made === null || (c.work_id !== null && made.has(c.work_id))),
      )
    },
    comment_channels: () => counted(studio.comments.map((c) => c.channel)),
    pending_comment_proposals: () => [],

    list_style_bricks: () => studio.bricks,
    style_brick_counts: () => counted(studio.bricks.map((b) => b.type_key)),
    style_brick_references: () => noAssets,
    style_slot_values: () => ({}),

    list_journal: () => studio.journal,
    unread_journal: () => studio.journal.filter((e) => e.read_at === null).length,
    list_deletions: () => studio.deletions,

    dismissed_findings: () => [],
    list_focus_notes: () => [],

    assistant_status: () => ({ available: true, version: '2.1.0', reason: null }),
    get_transcript: ({ chatId }) => {
      const chat = studio.chats.find((c) => c.id === chatId)
      if (chat === undefined) return null
      return {
        chat: {
          id: chat.id,
          profile_id: IDS.profile,
          work_id: chat.work_id,
          title: chat.title ?? null,
          session_id: null,
          created_at: EARLIER,
          updated_at: chat.updated_at,
        },
        messages: [
          {
            id: 'm-ask',
            chat_id: chat.id,
            role: 'user',
            body: 'Tighten the chorus',
            meta: {},
            created_at: EARLIER,
          },
          {
            id: 'm-answer',
            chat_id: chat.id,
            role: 'assistant',
            body: 'Cut the second line; the hook lands sooner.',
            meta: {},
            created_at: NOW,
          },
        ],
      }
    },
    list_runs: () => [],
    list_chat_summaries: ({ workId }) =>
      studio.chats.filter((c) => workId === undefined || c.work_id === workId),
    waiting_chats: () => [],
    pending_proposals: () => [],
    active_runs: () => [],
    active_tasks: () => [],
    task_queue: () => ({ running: [], waiting: [] }),
    list_plugins: () => [],

    workspace_path: () => 'C:\\Users\\someone\\AppData\\Roaming\\kilna\\workspace.db',
    suggested_backup_name: () => 'kilna-2026-09-15.db',
    mcp_registration: () => 'claude mcp add kilna -- kilna --mcp',
  }
}
