import type {
  Asset,
  ChatSummary,
  Collection,
  Comment,
  Cut,
  Deletion,
  JournalEntry,
  Link,
  Links,
  Note,
  Profile,
  ProfileConfig,
  Readiness,
  Release,
  Scene,
  ScheduledRelease,
  Score,
  ScoredWork,
  StyleBrick,
  Version,
  VersionSummary,
  Work,
} from '@/lib/api/types'
import type { Args, Handler } from '@/test/backend'
import music from '@/test/fixtures/profiles/music.json'

/*
 * A small studio, made up: two songs, the clip cut to the first and a short
 * cut from the clip. Every name is invented and English, as the project's
 * rule on demo data asks - nothing here is anyone's real work.
 *
 * The vocabulary is the shipped Studio profile, read the way the window reads
 * it (`fixtures/profiles/`, generated by the backend's own tests), so a
 * screen is drawn with the kinds, roles and axes a person actually has.
 */

/** The moment the fixture was "made": fixed, so a date on screen is too. */
export const NOW = '2026-09-15T10:00:00Z'
const EARLIER = '2026-09-01T10:00:00Z'

export const IDS = {
  profile: 'p-studio',
  song: 'w-lanterns',
  draft: 'w-harbour',
  video: 'w-lanterns-clip',
  short: 'w-lanterns-short',
  lyrics: 'v-lanterns-lyrics-2',
  lyricsFirst: 'v-lanterns-lyrics-1',
  style: 'v-lanterns-style',
  draftLyrics: 'v-harbour-lyrics',
  plot: 'v-clip-plot',
  score: 's-lanterns',
  audio: 'r-lanterns-audio',
  youtube: 'r-clip-youtube',
  note: 'n-idea',
  character: 'n-keeper',
  comment: 'c-first',
  brick: 'b-dusk',
  sceneOpen: 'sc-open',
  sceneClose: 'sc-close',
  cut: 'cut-chorus',
  link: 'l-clip-from-song',
  collection: 'col-first',
} as const

export interface Studio {
  profile: Profile
  works: Work[]
  versions: Version[]
  scores: Score[]
  releases: Release[]
  notes: Note[]
  comments: Comment[]
  bricks: StyleBrick[]
  scenes: Scene[]
  cuts: Cut[]
  links: Link[]
  collections: Collection[]
  journal: JournalEntry[]
  deletions: Deletion[]
  chats: ChatSummary[]
}

function work(fields: Partial<Work> & Pick<Work, 'id' | 'kind' | 'title'>): Work {
  return {
    profile_id: IDS.profile,
    collection_id: null,
    status: 'draft',
    status_pinned_at: null,
    meta: {},
    tags: [],
    marks: [],
    current_version_id: null,
    position: 0,
    tier_pinned: null,
    tier_pinned_at: null,
    tier_pin_reason: null,
    bookmarked_at: null,
    stage: null,
    cover: {},
    created_at: EARLIER,
    updated_at: NOW,
    ...fields,
  }
}

function version(
  fields: Partial<Version> & Pick<Version, 'id' | 'work_id' | 'role' | 'body'>,
): Version {
  return {
    revision: 1,
    label: null,
    meta: {},
    parent_version_id: null,
    created_at: EARLIER,
    ...fields,
  }
}

function release(fields: Partial<Release> & Pick<Release, 'id' | 'work_id' | 'kind'>): Release {
  return {
    status: 'planned',
    title: null,
    scheduled_at: null,
    released_at: null,
    url: null,
    slot_pinned_at: null,
    scheduled_time: null,
    time_zone: null,
    meta: {},
    created_at: EARLIER,
    updated_at: NOW,
    ...fields,
  }
}

/** A fresh studio: each call builds its own, so a test may change it freely. */
export function studio(): Studio {
  const profile: Profile = {
    id: IDS.profile,
    key: music.key,
    name: music.name,
    description: music.description,
    config: music.config as unknown as ProfileConfig,
    is_active: true,
    is_builtin: true,
  }

  const works = [
    work({
      id: IDS.song,
      kind: 'song',
      title: 'Paper Lanterns',
      status: 'scored',
      tags: ['night'],
      marks: ['working'],
      stage: 50,
      current_version_id: IDS.lyrics,
      collection_id: IDS.collection,
      meta: { bpm: '96', key: 'A minor', duration: '3:24', language: 'en' },
      position: 0,
    }),
    work({
      id: IDS.draft,
      kind: 'song',
      title: 'Harbour Lights',
      current_version_id: IDS.draftLyrics,
      position: 1,
    }),
    work({
      id: IDS.video,
      kind: 'video',
      title: 'Paper Lanterns (clip)',
      current_version_id: IDS.plot,
      meta: { duration: '3:24' },
      position: 2,
    }),
    work({ id: IDS.short, kind: 'short', title: 'Paper Lanterns (short)', position: 3 }),
  ]

  const versions = [
    version({
      id: IDS.lyricsFirst,
      work_id: IDS.song,
      role: 'lyrics',
      body: 'Lanterns on the water\nfloating out of reach',
    }),
    version({
      id: IDS.lyrics,
      work_id: IDS.song,
      role: 'lyrics',
      revision: 2,
      label: 'Second pass',
      parent_version_id: IDS.lyricsFirst,
      body: '[Verse]\nLanterns on the water\nfloating out of reach\n\n[Chorus]\nPaper, paper, carry the light',
      created_at: NOW,
    }),
    version({
      id: IDS.style,
      work_id: IDS.song,
      role: 'style',
      body: 'warm synth pop, slow build, airy female vocal',
    }),
    version({
      id: IDS.draftLyrics,
      work_id: IDS.draft,
      role: 'lyrics',
      body: 'Harbour lights are blinking\none by one',
    }),
    version({
      id: IDS.plot,
      work_id: IDS.video,
      role: 'plot',
      body: 'A girl lets a paper lantern go at dusk; the river carries it through the town.',
    }),
  ]

  const scores: Score[] = [
    {
      id: IDS.score,
      work_id: IDS.song,
      version_id: IDS.lyrics,
      axes: { hook: 8, lyrics: 7, emotion: 8, production: 6, originality: 7, visual: 9 },
      total: 7.5,
      tier: 'picture',
      note: 'The chorus carries it.',
      rater: null,
      scored_at: NOW,
      revision: 2,
    },
  ]

  const releases = [
    release({
      id: IDS.audio,
      work_id: IDS.song,
      kind: 'audio',
      status: 'scheduled',
      scheduled_at: '2026-09-22',
    }),
    release({ id: IDS.youtube, work_id: IDS.video, kind: 'youtube' }),
  ]

  const notes: Note[] = [
    {
      id: IDS.note,
      profile_id: IDS.profile,
      work_id: null,
      kind: 'note',
      title: 'A song about tides',
      body: 'Something about the tide going out and taking the day with it.\n\n- [ ] find a hook',
      tags: ['ideas'],
      created_at: EARLIER,
      updated_at: NOW,
    },
    {
      id: IDS.character,
      profile_id: IDS.profile,
      work_id: IDS.video,
      kind: 'character',
      title: 'The lantern keeper',
      body: 'An old man who sells lanterns by the bridge.',
      tags: [],
      created_at: EARLIER,
      updated_at: EARLIER,
    },
  ]

  const comments: Comment[] = [
    {
      id: IDS.comment,
      profile_id: IDS.profile,
      channel: 'YouTube',
      work_id: IDS.video,
      author: 'listener42',
      body: 'The shot on the bridge is beautiful.',
      reply: null,
      state: 'open',
      commented_on: '2026-09-14',
      created_at: NOW,
      updated_at: NOW,
    },
  ]

  const bricks: StyleBrick[] = [
    {
      id: IDS.brick,
      profile_id: IDS.profile,
      type_key: 'look',
      name: 'Dusk over water',
      description: 'Low sun, long reflections, teal and amber.',
      hint: null,
      status: 'ready',
      created_at: EARLIER,
      updated_at: NOW,
      reference_count: 0,
    },
  ]

  const scenes: Scene[] = [
    {
      id: IDS.sceneOpen,
      profile_id: IDS.profile,
      work_id: IDS.video,
      position: 1,
      section: 'Verse',
      starts_at: 0,
      ends_at: 12,
      shot_type: null,
      description: 'The lantern is lit on the riverbank.',
      blocks: { still: 'close-up of hands lighting a paper lantern at dusk' },
      created_at: EARLIER,
      updated_at: NOW,
    },
    {
      id: IDS.sceneClose,
      profile_id: IDS.profile,
      work_id: IDS.video,
      position: 2,
      section: 'Chorus',
      starts_at: 12,
      ends_at: 30,
      shot_type: null,
      description: 'The lantern drifts under the bridge.',
      blocks: {},
      created_at: EARLIER,
      updated_at: NOW,
    },
  ]

  const cuts: Cut[] = [
    {
      id: IDS.cut,
      profile_id: IDS.profile,
      work_id: IDS.short,
      source_id: IDS.video,
      starts_at: 12,
      ends_at: 30,
      position: 0,
      label: 'Chorus',
      created_at: EARLIER,
      updated_at: NOW,
      source_title: 'Paper Lanterns (clip)',
      source_duration: 204,
    },
  ]

  const links: Link[] = [
    {
      id: IDS.link,
      work_id: IDS.video,
      source_id: IDS.song,
      role: 'soundtrack',
      source_version_id: IDS.lyrics,
      created_at: EARLIER,
      source_title: 'Paper Lanterns',
      source_kind: 'song',
      source_status: 'scored',
      source_current_version_id: IDS.lyrics,
      taken_revision: 2,
      current_revision: 2,
      drifted: false,
    },
  ]

  const collections: Collection[] = [
    {
      id: IDS.collection,
      profile_id: IDS.profile,
      kind: 'album',
      title: 'Riverside',
      description: null,
      position: 0,
      meta: {},
      target_size: 8,
      due_on: null,
      created_at: EARLIER,
      updated_at: NOW,
      works: 1,
    },
  ]

  const journal: JournalEntry[] = [
    {
      id: 'j-created',
      action: 'work.created',
      params: { title: 'Harbour Lights' },
      level: 'info',
      entity: 'work',
      entity_id: IDS.draft,
      occurrences: 1,
      created_at: NOW,
      read_at: null,
    },
    {
      id: 'j-scored',
      action: 'score.added',
      params: { title: 'Paper Lanterns', total: 7.5 },
      level: 'info',
      entity: 'work',
      entity_id: IDS.song,
      occurrences: 1,
      created_at: EARLIER,
      read_at: EARLIER,
    },
  ]

  const deletions: Deletion[] = [
    {
      id: 'd-old-note',
      entity: 'note',
      entity_id: 'n-old',
      label: 'An old idea',
      origin: null,
      reason: 'deleted',
      deleted_at: NOW,
      restorable: true,
    },
  ]

  const chats: ChatSummary[] = [
    {
      id: 'chat-lanterns',
      work_id: IDS.song,
      work_title: 'Paper Lanterns',
      title: 'Tighten the chorus',
      first_prompt: 'Tighten the chorus',
      cost_usd: 0.02,
      updated_at: NOW,
    },
  ]

  return {
    profile,
    works,
    versions,
    scores,
    releases,
    notes,
    comments,
    bricks,
    scenes,
    cuts,
    links,
    collections,
    journal,
    deletions,
    chats,
  }
}

const byWork =
  <T extends { work_id: string | null }>(rows: () => T[]) =>
  ({ workId }: Args) =>
    rows().filter((row) => row.work_id === workId)

/** Whether a song has what its release needs: the tests do not judge it. */
const READY: Readiness = { roles: [], scored: true, ready: true }

function scheduled(studio: Studio, release: Release): ScheduledRelease {
  const owner = studio.works.find((w) => w.id === release.work_id)
  const score = studio.scores.find((s) => s.work_id === release.work_id)
  return {
    ...release,
    work_title: owner?.title ?? '',
    work_kind: owner?.kind ?? '',
    total: score?.total ?? null,
    tier: score?.tier ?? null,
    readiness: READY,
    work_stage: owner?.stage ?? null,
  }
}

function summary(studio: Studio, row: Version): VersionSummary {
  const owner = studio.works.find((w) => w.id === row.work_id)
  return {
    id: row.id,
    work_id: row.work_id,
    role: row.role,
    revision: row.revision,
    label: row.label,
    length: row.body.length,
    parent_version_id: row.parent_version_id,
    created_at: row.created_at,
    is_current: owner?.current_version_id === row.id,
    about_version_id: null,
  }
}

function scored(studio: Studio, row: Work): ScoredWork {
  const score = studio.scores.find((s) => s.work_id === row.id)
  const releases = studio.releases.filter((r) => r.work_id === row.id)
  return {
    work_id: row.id,
    title: row.title,
    kind: row.kind,
    status: row.status,
    tier_pinned: row.tier_pinned !== null,
    total: score?.total ?? null,
    tier: row.tier_pinned ?? score?.tier ?? null,
    scored_at: score?.scored_at ?? null,
    stale: false,
    released: releases.filter((r) => r.released_at !== null).length,
    scheduled: releases.filter((r) => r.scheduled_at !== null).length,
    updated_at: row.updated_at,
    created_at: row.created_at,
    collection_id: row.collection_id,
    tags: row.tags,
    marks: row.marks,
    bookmarked_at: row.bookmarked_at,
    version_count: studio.versions.filter((v) => v.work_id === row.id).length,
    stage: row.stage,
  }
}

function linksOf(studio: Studio, workId: string): Links {
  return {
    sources: studio.links.filter((link) => link.work_id === workId),
    derived: studio.links
      .filter((link) => link.source_id === workId)
      .map((link) => {
        const derived = studio.works.find((w) => w.id === link.work_id)
        return {
          link_id: link.id,
          work_id: link.work_id,
          title: derived?.title ?? '',
          kind: derived?.kind ?? '',
          status: derived?.status ?? '',
          role: link.role,
          created_at: link.created_at,
        }
      }),
  }
}

function counted(values: string[]): [string, number][] {
  const counts = new Map<string, number>()
  for (const value of values) counts.set(value, (counts.get(value) ?? 0) + 1)
  return [...counts.entries()].sort(([a], [b]) => a.localeCompare(b))
}

/**
 * The answers to every question a screen asks on its way in, read off the
 * studio. Reads only: a test about a write answers that command itself, and
 * says what the write should have been.
 */
export function answersFor(studio: Studio): Record<string, Handler> {
  const noAssets: Asset[] = []
  return {
    get_workspace: () => ({
      schema_version: 30,
      profile: studio.profile,
      works: studio.works.length,
      releases: studio.releases.length,
    }),
    list_profiles: () => [studio.profile],
    warn_unready_releases: () => 0,
    last_undoable: () => null,

    catalogue: () => studio.works.map((row) => scored(studio, row)),
    list_works: () => studio.works,
    get_work: ({ id }) => studio.works.find((w) => w.id === id) ?? null,
    work_tags: () => counted(studio.works.flatMap((w) => w.tags)),
    works_matching: () => [],
    search: () => [],
    status_drift: () => [],
    list_collections: () => studio.collections,
    list_covers: () => [],

    list_versions: ({ workId }) =>
      studio.versions.filter((v) => v.work_id === workId).map((v) => summary(studio, v)),
    get_version: ({ id }) => studio.versions.find((v) => v.id === id) ?? null,
    resolve_links: () => [],

    score_history: byWork(() => studio.scores),
    latest_score: ({ workId }) => studio.scores.find((s) => s.work_id === workId) ?? null,
    kind_verdicts: () => [],

    calendar: () =>
      studio.releases.filter((r) => r.scheduled_at !== null).map((r) => scheduled(studio, r)),
    release_queue: () =>
      studio.releases.filter((r) => r.scheduled_at === null).map((r) => scheduled(studio, r)),
    releases_for_work: ({ workId }) =>
      studio.releases.filter((r) => r.work_id === workId).map((r) => scheduled(studio, r)),
    release_fields: () => [],
    list_release_assets: () => noAssets,
    can_export_package: () => true,

    list_links: ({ workId }) => linksOf(studio, workId as string),
    list_scenes: byWork(() => studio.scenes),
    list_scene_notes: () => [],
    list_scene_frames: () => [],
    list_cuts: byWork(() => studio.cuts),
    list_cuts_from: ({ sourceId }) => studio.cuts.filter((c) => c.source_id === sourceId),
    cut_shot_list: () => [],
    list_work_assets: () => noAssets,

    list_notes: ({ filter }) => {
      const wanted = (filter ?? {}) as { work_id?: string; kind?: string; tag?: string }
      return studio.notes.filter(
        (note) =>
          (wanted.work_id === undefined || note.work_id === wanted.work_id) &&
          (wanted.kind === undefined || note.kind === wanted.kind) &&
          (wanted.tag === undefined || note.tags.includes(wanted.tag)),
      )
    },
    list_tags: () => counted(studio.notes.flatMap((n) => n.tags)),

    list_comments: ({ filter }) => {
      const wanted = (filter ?? {}) as { work_id?: string }
      return studio.comments.filter(
        (c) => wanted.work_id === undefined || c.work_id === wanted.work_id,
      )
    },
    comment_channels: () => counted(studio.comments.map((c) => c.channel)),
    count_work_comments: ({ workId }) => {
      const mine = studio.comments.filter((c) => c.work_id === workId)
      return { total: mine.length, waiting: mine.filter((c) => c.state === 'open').length }
    },
    pending_comment_proposals: () => [],

    list_style_bricks: () => studio.bricks,
    style_brick_counts: () => counted(studio.bricks.map((b) => b.type_key)),
    style_brick_references: () => noAssets,

    list_journal: () => studio.journal,
    journal_for_work: ({ workId }) => studio.journal.filter((e) => e.entity_id === workId),
    unread_journal: () => studio.journal.filter((e) => e.read_at === null).length,
    list_deletions: () => studio.deletions,

    dismissed_findings: () => [],
    list_focus_notes: () => [],

    assistant_status: () => ({ available: true, version: '2.1.0', reason: null }),
    get_transcript: ({ chatId }) => {
      const chat = studio.chats.find((c) => c.id === chatId)
      if (chat === undefined) return null
      return {
        chat: {
          id: chat.id,
          profile_id: IDS.profile,
          work_id: chat.work_id,
          title: chat.title ?? null,
          session_id: null,
          created_at: EARLIER,
          updated_at: chat.updated_at,
        },
        messages: [
          {
            id: 'm-ask',
            chat_id: chat.id,
            role: 'user',
            body: 'Tighten the chorus',
            meta: {},
            created_at: EARLIER,
          },
          {
            id: 'm-answer',
            chat_id: chat.id,
            role: 'assistant',
            body: 'Cut the second line; the hook lands sooner.',
            meta: {},
            created_at: NOW,
          },
        ],
      }
    },
    list_runs: () => [],
    list_chat_summaries: ({ workId }) =>
      studio.chats.filter((c) => workId === undefined || c.work_id === workId),
    waiting_chats: () => [],
    pending_proposals: () => [],
    active_runs: () => [],
    active_tasks: () => [],
    task_queue: () => ({ running: [], waiting: [] }),
    list_plugins: () => [],

    workspace_path: () => 'C:\\Users\\someone\\AppData\\Roaming\\kilna\\workspace.db',
    suggested_backup_name: () => 'kilna-2026-09-15.db',
    mcp_registration: () => 'claude mcp add kilna -- kilna --mcp',
  }
}
